"use server";

import { revalidatePath } from "next/cache";
import { Types } from "mongoose";

import { getAdminAccess } from "@/lib/admin/access";
import { connectToDatabase } from "@/lib/db/mongodb";
import { LearningCourse } from "@/models/learning/course";
import { LearningLesson } from "@/models/learning/lesson";
import { LearningLevel } from "@/models/learning/level";
import { LearningUnit } from "@/models/learning/unit";
import { FillBlankExercise, MatchingExercise, MultipleChoiceExercise, OrderingExercise, PracticeExercise } from "@/models/practice/exercise";
import { PracticeSet } from "@/models/practice/set";
import { practiceExerciseSchema, practiceSetSchema, statusSchema } from "@/validation/admin/content";
import type { AdminActionResult } from "@/actions/admin/content";
import type { PracticeExerciseRecord } from "@/models/practice/types";

function value(fd: FormData, key: string) { const item = fd.get(key); return typeof item === "string" ? item.trim() : ""; }
function objectId(id: string) { return Types.ObjectId.isValid(id) ? new Types.ObjectId(id) : null; }
function parseJson(fd: FormData, key: string) { try { return JSON.parse(value(fd, key)); } catch { return undefined; } }
function errors(error: { issues: Array<{ path: PropertyKey[]; message: string }> }): AdminActionResult { const fieldErrors: Record<string, string[]> = {}; for (const issue of error.issues) { const key = issue.path.map(String).join(".") || "form"; fieldErrors[key] ??= []; fieldErrors[key].push(issue.message); } return { ok: false, code: "INVALID", fieldErrors }; }
function duplicate(error: unknown, label: string): AdminActionResult { if (typeof error === "object" && error !== null && "code" in error && error.code === 11000) return { ok: false, code: "DUPLICATE", fieldErrors: { order: [`That ${label} order or slug already exists.`] } }; console.error(`Unable to save admin ${label}.`, error); return { ok: false, code: "DATABASE" }; }
async function admin(): Promise<true | "UNAUTHORIZED" | "FORBIDDEN"> { const access = await getAdminAccess(); return access.ok ? true : access.code; }
function revalidate() { revalidatePath("/[locale]/admin", "layout"); revalidatePath("/[locale]/practice", "layout"); }

export async function createPracticeSet(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = practiceSetSchema.safeParse({ lessonId: value(fd, "lessonId"), slug: value(fd, "slug"), title: { fa: value(fd, "titleFa"), en: value(fd, "titleEn") }, description: { fa: value(fd, "descriptionFa"), en: value(fd, "descriptionEn") }, order: value(fd, "order") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); if (!await LearningLesson.exists({ _id: objectId(parsed.data.lessonId) })) return { ok: false, code: "INVALID", fieldErrors: { lessonId: ["The lesson does not exist."] } }; const created = await PracticeSet.create({ ...parsed.data, lessonId: objectId(parsed.data.lessonId), status: "draft" }); revalidate(); return { ok: true, id: created._id.toString() }; } catch (e) { return duplicate(e, "practice set"); } }
export async function updatePracticeSet(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const id = objectId(value(fd, "id")); const parsed = practiceSetSchema.safeParse({ lessonId: value(fd, "lessonId"), slug: value(fd, "slug"), title: { fa: value(fd, "titleFa"), en: value(fd, "titleEn") }, description: { fa: value(fd, "descriptionFa"), en: value(fd, "descriptionEn") }, order: value(fd, "order") }); if (!id) return { ok: false, code: "INVALID" }; if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const updated = await PracticeSet.findByIdAndUpdate(id, { $set: { ...parsed.data, lessonId: objectId(parsed.data.lessonId) } }, { new: true, runValidators: true }).exec(); if (!updated) return { ok: false, code: "NOT_FOUND" }; revalidate(); return { ok: true, id: id.toString() }; } catch (e) { return duplicate(e, "practice set"); } }
export async function setPracticeSetStatus(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = statusSchema.safeParse({ id: value(fd, "id"), status: value(fd, "status") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const set = await PracticeSet.findById(parsed.data.id).lean().exec(); if (!set) return { ok: false, code: "NOT_FOUND" }; if (parsed.data.status === "published") { const lesson = await LearningLesson.findOne({ _id: set.lessonId, status: "published" }).lean().exec(); const unit = lesson && await LearningUnit.findOne({ _id: lesson.unitId, status: "published" }).lean().exec(); const course = unit && await LearningCourse.findOne({ _id: unit.courseId, status: "published" }).lean().exec(); const parent = course && await LearningLevel.exists({ _id: course.levelId, status: "published" }); const exercises = await PracticeExercise.countDocuments({ practiceSetId: set._id, status: "published" }); if (!parent || !lesson || !unit || !course || exercises < 1) return { ok: false, code: "INVALID", fieldErrors: { status: ["A practice set needs a published lesson and at least one published exercise."] } }; } await PracticeSet.updateOne({ _id: set._id }, { $set: { status: parsed.data.status } }).exec(); revalidate(); return { ok: true, id: parsed.data.id }; } catch (e) { return duplicate(e, "practice set"); } }

export async function createPracticeExercise(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = practiceExerciseSchema.safeParse(parseJson(fd, "payload")); if (!parsed.success) return errors(parsed.error); const semantic = validateExercise(parsed.data); if (semantic) return semantic; try { await connectToDatabase(); if (!await PracticeSet.exists({ _id: objectId(parsed.data.practiceSetId) })) return { ok: false, code: "INVALID", fieldErrors: { practiceSetId: ["The practice set does not exist."] } }; const model = exerciseModel(parsed.data.exerciseType); const created = await model.create({ ...parsed.data, practiceSetId: objectId(parsed.data.practiceSetId), status: "draft" }); revalidate(); return { ok: true, id: created._id.toString() }; } catch (e) { return duplicate(e, "practice exercise"); } }
export async function updatePracticeExercise(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const id = objectId(value(fd, "id")); const parsed = practiceExerciseSchema.safeParse(parseJson(fd, "payload")); if (!id) return { ok: false, code: "INVALID" }; if (!parsed.success) return errors(parsed.error); const semantic = validateExercise(parsed.data); if (semantic) return semantic; try { await connectToDatabase(); const updated = await PracticeExercise.findByIdAndUpdate(id, { $set: { ...parsed.data, practiceSetId: objectId(parsed.data.practiceSetId) } }, { new: true, runValidators: true }).exec(); if (!updated) return { ok: false, code: "NOT_FOUND" }; revalidate(); return { ok: true, id: id.toString() }; } catch (e) { return duplicate(e, "practice exercise"); } }
export async function setPracticeExerciseStatus(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = statusSchema.safeParse({ id: value(fd, "id"), status: value(fd, "status") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const exercise = await PracticeExercise.findById(parsed.data.id).lean<PracticeExerciseRecord>().exec(); if (!exercise) return { ok: false, code: "NOT_FOUND" }; if (parsed.data.status === "published") { const semantic = validateExercise(exercise); if (semantic) return semantic; if (!await PracticeSet.exists({ _id: exercise.practiceSetId, status: "published" })) return { ok: false, code: "INVALID", fieldErrors: { status: ["The parent practice set must be published first."] } }; } await PracticeExercise.updateOne({ _id: exercise._id }, { $set: { status: parsed.data.status } }).exec(); revalidate(); return { ok: true, id: parsed.data.id }; } catch (e) { return duplicate(e, "practice exercise"); } }

function exerciseModel(type: PracticeExerciseRecord["exerciseType"]) { if (type === "multiple-choice") return MultipleChoiceExercise; if (type === "fill-blank") return FillBlankExercise; if (type === "matching") return MatchingExercise; return OrderingExercise; }
function idsUnique(ids: string[]) { return new Set(ids).size === ids.length && ids.every(Boolean); }
function validateExercise(valueToCheck: PracticeExerciseRecord | Record<string, unknown>): AdminActionResult | null {
  const type = valueToCheck.exerciseType;
  if (type === "multiple-choice") { const options = valueToCheck.options as Array<{ id: string }> | undefined; const correct = valueToCheck.correctOptionId; if (!options || !idsUnique(options.map((item) => item.id)) || typeof correct !== "string" || !options.some((item) => item.id === correct)) return { ok: false, code: "INVALID", fieldErrors: { payload: ["Multiple choice needs unique options and one matching correctOptionId."] } }; }
  if (type === "fill-blank") { const answers = valueToCheck.acceptedAnswers as string[] | undefined; if (!answers?.length || answers.some((item) => !item.trim())) return { ok: false, code: "INVALID", fieldErrors: { payload: ["Fill blank needs at least one accepted answer."] } }; }
  if (type === "matching") { const left = valueToCheck.leftItems as Array<{ id: string }> | undefined; const right = valueToCheck.rightItems as Array<{ id: string }> | undefined; const pairs = valueToCheck.pairs as Array<{ leftId: string; rightId: string }> | undefined; if (!left?.length || !right?.length || !pairs?.length || !idsUnique(left.map((item) => item.id)) || !idsUnique(right.map((item) => item.id)) || pairs.some((pair) => !left.some((item) => item.id === pair.leftId) || !right.some((item) => item.id === pair.rightId))) return { ok: false, code: "INVALID", fieldErrors: { payload: ["Matching needs known unique item ids and valid pairs."] } }; }
  if (type === "ordering") { const items = valueToCheck.items as Array<{ id: string }> | undefined; const correct = valueToCheck.correctOrder as string[] | undefined; if (!items?.length || !correct?.length || !idsUnique(items.map((item) => item.id)) || correct.length !== items.length || new Set(correct).size !== correct.length || correct.some((id) => !items.some((item) => item.id === id))) return { ok: false, code: "INVALID", fieldErrors: { payload: ["Ordering needs a unique complete correctOrder."] } }; }
  return null;
}
