"use server";

import { revalidatePath } from "next/cache";
import { Types } from "mongoose";

import { getAdminAccess } from "@/lib/admin/access";
import { connectToDatabase } from "@/lib/db/mongodb";
import { LearningCourse } from "@/models/learning/course";
import { LearningLesson } from "@/models/learning/lesson";
import { LearningLevel } from "@/models/learning/level";
import { LearningUnit } from "@/models/learning/unit";
import { learningCourseSchema, learningLessonSchema, learningLevelSchema, learningUnitSchema, statusSchema } from "@/validation/admin/content";
import type { AdminActionResult } from "@/actions/admin/content";

function value(fd: FormData, key: string) { const item = fd.get(key); return typeof item === "string" ? item.trim() : ""; }
function localized(fd: FormData, key: string) { return { fa: value(fd, `${key}Fa`), en: value(fd, `${key}En`) }; }
function objectId(id: string) { return Types.ObjectId.isValid(id) ? new Types.ObjectId(id) : null; }
function errors(error: { issues: Array<{ path: PropertyKey[]; message: string }> }): AdminActionResult { const fieldErrors: Record<string, string[]> = {}; for (const issue of error.issues) { const key = issue.path.map(String).join(".") || "form"; fieldErrors[key] ??= []; fieldErrors[key].push(issue.message); } return { ok: false, code: "INVALID", fieldErrors }; }
function duplicate(error: unknown, label: string): AdminActionResult { if (typeof error === "object" && error !== null && "code" in error && error.code === 11000) return { ok: false, code: "DUPLICATE", fieldErrors: { slug: [`That ${label} slug or order already exists.`] } }; console.error(`Unable to save admin ${label}.`, error); return { ok: false, code: "DATABASE" }; }
async function admin(): Promise<true | "UNAUTHORIZED" | "FORBIDDEN"> { const access = await getAdminAccess(); return access.ok ? true : access.code; }
function revalidate() { revalidatePath("/[locale]/admin", "layout"); revalidatePath("/[locale]/learn", "layout"); revalidatePath("/[locale]/practice", "layout"); }
function parseJson(fd: FormData, key: string) { try { return JSON.parse(value(fd, key) || "[]"); } catch { return undefined; } }

export async function createLearningLevel(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = learningLevelSchema.safeParse({ code: value(fd, "code"), slug: value(fd, "slug"), title: localized(fd, "title"), description: localized(fd, "description"), order: value(fd, "order") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const created = await LearningLevel.create({ ...parsed.data, status: "draft" }); revalidate(); return { ok: true, id: created._id.toString() }; } catch (e) { return duplicate(e, "level"); } }
export async function updateLearningLevel(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const id = objectId(value(fd, "id")); const parsed = learningLevelSchema.safeParse({ code: value(fd, "code"), slug: value(fd, "slug"), title: localized(fd, "title"), description: localized(fd, "description"), order: value(fd, "order") }); if (!id) return { ok: false, code: "INVALID" }; if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const updated = await LearningLevel.findByIdAndUpdate(id, { $set: parsed.data }, { new: true, runValidators: true }).exec(); if (!updated) return { ok: false, code: "NOT_FOUND" }; revalidate(); return { ok: true, id: id.toString() }; } catch (e) { return duplicate(e, "level"); } }
export async function setLearningLevelStatus(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; return setLevelStatus(fd); }
async function setLevelStatus(fd: FormData): Promise<AdminActionResult> { const parsed = statusSchema.safeParse({ id: value(fd, "id"), status: value(fd, "status") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const level = await LearningLevel.findById(parsed.data.id).lean().exec(); if (!level) return { ok: false, code: "NOT_FOUND" }; if (parsed.data.status === "published" && (!level.title?.fa || !level.title?.en || !level.description?.fa || !level.description?.en)) return { ok: false, code: "INVALID", fieldErrors: { status: ["A level needs bilingual title and description before publishing."] } }; await LearningLevel.updateOne({ _id: parsed.data.id }, { $set: { status: parsed.data.status } }).exec(); revalidate(); return { ok: true, id: parsed.data.id }; } catch (e) { return duplicate(e, "level"); } }

export async function createLearningCourse(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = learningCourseSchema.safeParse({ levelId: value(fd, "levelId"), slug: value(fd, "slug"), title: localized(fd, "title"), description: localized(fd, "description"), order: value(fd, "order") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const parent = await LearningLevel.exists({ _id: objectId(parsed.data.levelId) }); if (!parent) return { ok: false, code: "INVALID", fieldErrors: { levelId: ["The level does not exist."] } }; const created = await LearningCourse.create({ ...parsed.data, levelId: objectId(parsed.data.levelId), status: "draft" }); revalidate(); return { ok: true, id: created._id.toString() }; } catch (e) { return duplicate(e, "course"); } }
export async function updateLearningCourse(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const id = objectId(value(fd, "id")); const parsed = learningCourseSchema.safeParse({ levelId: value(fd, "levelId"), slug: value(fd, "slug"), title: localized(fd, "title"), description: localized(fd, "description"), order: value(fd, "order") }); if (!id) return { ok: false, code: "INVALID" }; if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const parent = await LearningLevel.exists({ _id: objectId(parsed.data.levelId) }); if (!parent) return { ok: false, code: "INVALID", fieldErrors: { levelId: ["The level does not exist."] } }; const updated = await LearningCourse.findByIdAndUpdate(id, { $set: { ...parsed.data, levelId: objectId(parsed.data.levelId) } }, { new: true, runValidators: true }).exec(); if (!updated) return { ok: false, code: "NOT_FOUND" }; revalidate(); return { ok: true, id: id.toString() }; } catch (e) { return duplicate(e, "course"); } }
export async function setLearningCourseStatus(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = statusSchema.safeParse({ id: value(fd, "id"), status: value(fd, "status") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const course = await LearningCourse.findById(parsed.data.id).lean().exec(); if (!course) return { ok: false, code: "NOT_FOUND" }; if (parsed.data.status === "published" && !await LearningLevel.exists({ _id: course.levelId, status: "published" })) return { ok: false, code: "INVALID", fieldErrors: { status: ["The parent level must be published first."] } }; await LearningCourse.updateOne({ _id: parsed.data.id }, { $set: { status: parsed.data.status } }).exec(); revalidate(); return { ok: true, id: parsed.data.id }; } catch (e) { return duplicate(e, "course"); } }

export async function createLearningUnit(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = learningUnitSchema.safeParse({ courseId: value(fd, "courseId"), slug: value(fd, "slug"), title: localized(fd, "title"), description: localized(fd, "description"), order: value(fd, "order") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); if (!await LearningCourse.exists({ _id: objectId(parsed.data.courseId) })) return { ok: false, code: "INVALID", fieldErrors: { courseId: ["The course does not exist."] } }; const created = await LearningUnit.create({ ...parsed.data, courseId: objectId(parsed.data.courseId), status: "draft" }); revalidate(); return { ok: true, id: created._id.toString() }; } catch (e) { return duplicate(e, "unit"); } }
export async function updateLearningUnit(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const id = objectId(value(fd, "id")); const parsed = learningUnitSchema.safeParse({ courseId: value(fd, "courseId"), slug: value(fd, "slug"), title: localized(fd, "title"), description: localized(fd, "description"), order: value(fd, "order") }); if (!id) return { ok: false, code: "INVALID" }; if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); if (!await LearningCourse.exists({ _id: objectId(parsed.data.courseId) })) return { ok: false, code: "INVALID", fieldErrors: { courseId: ["The course does not exist."] } }; const updated = await LearningUnit.findByIdAndUpdate(id, { $set: { ...parsed.data, courseId: objectId(parsed.data.courseId) } }, { new: true, runValidators: true }).exec(); if (!updated) return { ok: false, code: "NOT_FOUND" }; revalidate(); return { ok: true, id: id.toString() }; } catch (e) { return duplicate(e, "unit"); } }
export async function setLearningUnitStatus(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = statusSchema.safeParse({ id: value(fd, "id"), status: value(fd, "status") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const unit = await LearningUnit.findById(parsed.data.id).lean().exec(); if (!unit) return { ok: false, code: "NOT_FOUND" }; if (parsed.data.status === "published") { const course = await LearningCourse.findOne({ _id: unit.courseId, status: "published" }).lean().exec(); if (!course || !await LearningLevel.exists({ _id: course.levelId, status: "published" })) return { ok: false, code: "INVALID", fieldErrors: { status: ["The published course and level parents are required first."] } }; } await LearningUnit.updateOne({ _id: parsed.data.id }, { $set: { status: parsed.data.status } }).exec(); revalidate(); return { ok: true, id: parsed.data.id }; } catch (e) { return duplicate(e, "unit"); } }

export async function createLearningLesson(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = learningLessonSchema.safeParse({ unitId: value(fd, "unitId"), slug: value(fd, "slug"), title: localized(fd, "title"), description: localized(fd, "description"), order: value(fd, "order"), estimatedDuration: value(fd, "estimatedDuration") || undefined, objectives: parseJson(fd, "objectives"), content: parseJson(fd, "content") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); if (!await LearningUnit.exists({ _id: objectId(parsed.data.unitId) })) return { ok: false, code: "INVALID", fieldErrors: { unitId: ["The unit does not exist."] } }; const created = await LearningLesson.create({ ...parsed.data, unitId: objectId(parsed.data.unitId), status: "draft" }); revalidate(); return { ok: true, id: created._id.toString() }; } catch (e) { return duplicate(e, "lesson"); } }
export async function updateLearningLesson(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const id = objectId(value(fd, "id")); const parsed = learningLessonSchema.safeParse({ unitId: value(fd, "unitId"), slug: value(fd, "slug"), title: localized(fd, "title"), description: localized(fd, "description"), order: value(fd, "order"), estimatedDuration: value(fd, "estimatedDuration") || undefined, objectives: parseJson(fd, "objectives"), content: parseJson(fd, "content") }); if (!id) return { ok: false, code: "INVALID" }; if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); if (!await LearningUnit.exists({ _id: objectId(parsed.data.unitId) })) return { ok: false, code: "INVALID", fieldErrors: { unitId: ["The unit does not exist."] } }; const updated = await LearningLesson.findByIdAndUpdate(id, { $set: { ...parsed.data, unitId: objectId(parsed.data.unitId) } }, { new: true, runValidators: true }).exec(); if (!updated) return { ok: false, code: "NOT_FOUND" }; revalidate(); return { ok: true, id: id.toString() }; } catch (e) { return duplicate(e, "lesson"); } }
export async function setLearningLessonStatus(_p: AdminActionResult | null, fd: FormData): Promise<AdminActionResult> { const access = await admin(); if (access !== true) return { ok: false, code: access }; const parsed = statusSchema.safeParse({ id: value(fd, "id"), status: value(fd, "status") }); if (!parsed.success) return errors(parsed.error); try { await connectToDatabase(); const lesson = await LearningLesson.findById(parsed.data.id).lean().exec(); if (!lesson) return { ok: false, code: "NOT_FOUND" }; if (parsed.data.status === "published") { const unit = await LearningUnit.findOne({ _id: lesson.unitId, status: "published" }).lean().exec(); const course = unit && await LearningCourse.findOne({ _id: unit.courseId, status: "published" }).lean().exec(); const level = course && await LearningLevel.exists({ _id: course.levelId, status: "published" }); if (!lesson.content.length || !unit || !course || !level) return { ok: false, code: "INVALID", fieldErrors: { status: ["The lesson needs content and published unit, course, and level parents."] } }; } await LearningLesson.updateOne({ _id: parsed.data.id }, { $set: { status: parsed.data.status } }).exec(); revalidate(); return { ok: true, id: parsed.data.id }; } catch (e) { return duplicate(e, "lesson"); } }
