import { getTranslations } from "next-intl/server";

import { PracticeExerciseForm, PracticeSetForm, PracticeStatusForm } from "@/components/admin/practice-form";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Link } from "@/i18n/navigation";
import { getAdminPracticeData } from "@/lib/db/admin";
import { createPracticeExercise, createPracticeSet, setPracticeExerciseStatus, setPracticeSetStatus, updatePracticeExercise, updatePracticeSet } from "@/actions/admin-practice";

function objectId(value: unknown) { return value && typeof value === "object" && "toString" in value ? String(value) : value; }
function exerciseJson(exercise: Record<string, unknown>) { const copy: Record<string, unknown> = { ...exercise }; for (const key of ["_id", "status", "createdAt", "updatedAt"]) delete copy[key]; copy.practiceSetId = objectId(copy.practiceSetId); return JSON.stringify(copy, null, 2); }

export default async function AdminPracticePage({ searchParams }: { searchParams: Promise<{ setId?: string; exerciseId?: string }> }) {
  const [t, data, query] = await Promise.all([getTranslations("admin"), getAdminPracticeData(), searchParams]);
  const setToEdit = data.sets.find((item) => item._id.toString() === query.setId);
  const exerciseToEdit = data.exercises.find((item) => item._id.toString() === query.exerciseId);
  return <div><div><p className="text-label text-gold">{t("practice")}</p><h1 className="text-h2 mt-2">{t("practice")}</h1><p className="text-body-sm mt-3 text-muted-foreground">{t("help.draft")}</p></div><div className="mt-8 grid gap-6 xl:grid-cols-2"><PracticeSetForm action={setToEdit ? updatePracticeSet : createPracticeSet} initial={setToEdit ? { id: setToEdit._id.toString(), lessonId: String(setToEdit.lessonId), slug: setToEdit.slug, titleFa: setToEdit.title.fa, titleEn: setToEdit.title.en, descriptionFa: setToEdit.description.fa, descriptionEn: setToEdit.description.en, order: String(setToEdit.order) } : undefined} /><PracticeExerciseForm action={exerciseToEdit ? updatePracticeExercise : createPracticeExercise} initial={exerciseToEdit ? exerciseJson(exerciseToEdit as unknown as Record<string, unknown>) : ""} /></div><div className="mt-8 grid gap-5"><Card><CardHeader><CardTitle>Practice sets</CardTitle></CardHeader><CardContent className="grid gap-4">{data.sets.map((set) => <div key={set._id.toString()} className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-4 last:border-0 last:pb-0"><div><p className="font-medium">{set.title.en}</p><p className="text-caption text-muted-foreground">{set.slug} · {set.status}</p></div><div className="flex flex-wrap gap-2"><Link href={`/admin/practice?setId=${set._id.toString()}`} className="rounded-lg border px-3 py-2 text-body-sm hover:bg-muted">{t("open")}</Link><PracticeStatusForm id={set._id.toString()} status={set.status} action={setPracticeSetStatus} /></div></div>)}{!data.sets.length ? <p className="text-body-sm text-muted-foreground">{t("noResults")}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Practice exercises</CardTitle></CardHeader><CardContent className="grid gap-4">{data.exercises.map((exercise) => <div key={exercise._id.toString()} className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-4 last:border-0 last:pb-0"><div><p className="font-medium">{exercise.exerciseType}</p><p className="text-caption text-muted-foreground">{exercise._id.toString()} · {exercise.status}</p></div><div className="flex flex-wrap gap-2"><Link href={`/admin/practice?exerciseId=${exercise._id.toString()}`} className="rounded-lg border px-3 py-2 text-body-sm hover:bg-muted">{t("open")}</Link><PracticeStatusForm id={exercise._id.toString()} status={exercise.status} action={setPracticeExerciseStatus} /></div></div>)}{!data.exercises.length ? <p className="text-body-sm text-muted-foreground">{t("noResults")}</p> : null}</CardContent></Card></div></div>;
}
