"use client";

import { useActionState } from "react";
import { useTranslations } from "next-intl";

import type { AdminActionResult } from "@/actions/admin/content";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { ContentStatus } from "@/models/domain/common";

type Entity = "level" | "course" | "unit" | "lesson";
type Action = (previous: AdminActionResult | null, formData: FormData) => Promise<AdminActionResult>;
type Values = Record<string, unknown> & { id?: string; status?: ContentStatus };

function text(values: Values, key: string) { const item = values[key]; return typeof item === "string" || typeof item === "number" ? String(item) : ""; }
function nested(values: Values, key: string, lang: "fa" | "en") { const item = values[key]; if (!item || typeof item !== "object") return ""; const value = (item as Record<string, unknown>)[lang]; return typeof value === "string" ? value : ""; }
function json(values: Values, key: string) { return JSON.stringify(values[key] ?? [], null, 2); }

export function CurriculumForm({ entity, initial, action, edit }: { entity: Entity; initial: Values; action: Action;edit: boolean }) {
  const t = useTranslations("admin");
  const [state, formAction, pending] = useActionState<AdminActionResult | null, FormData>(action, null);
  const label = entity === "level" ? "Level" : entity === "course" ? "Course" : entity === "unit" ? "Unit" : "Lesson";
  return <form action={formAction} className="grid gap-6"><input type="hidden" name="id" value={text(initial, "id")} /><Card><CardHeader><CardTitle>{edit ? t("edit") : t("new")} {label}</CardTitle></CardHeader><CardContent className="grid gap-5">{entity === "level" ? <><div className="grid gap-4 sm:grid-cols-2"><Field label="Code" name="code" defaultValue={text(initial, "code")} required /><Field label={t("fields.slug")} name="slug" defaultValue={text(initial, "slug")} required /></div><Localized values={initial} name="title" titleFa={t("fields.titleFa")} titleEn={t("fields.titleEn")} /><Localized values={initial} name="description" titleFa={t("fields.descriptionFa")} titleEn={t("fields.descriptionEn")} multi /></> : null}{entity === "course" ? <><Field label="Level id" name="levelId" defaultValue={text(initial, "levelId")} required /><Field label={t("fields.slug")} name="slug" defaultValue={text(initial, "slug")} required /><Localized values={initial} name="title" titleFa={t("fields.titleFa")} titleEn={t("fields.titleEn")} /><Localized values={initial} name="description" titleFa={t("fields.descriptionFa")} titleEn={t("fields.descriptionEn")} multi /></> : null}{entity === "unit" ? <><Field label="Course id" name="courseId" defaultValue={text(initial, "courseId")} required /><Field label={t("fields.slug")} name="slug" defaultValue={text(initial, "slug")} required /><Localized values={initial} name="title" titleFa={t("fields.titleFa")} titleEn={t("fields.titleEn")} /><Localized values={initial} name="description" titleFa={t("fields.descriptionFa")} titleEn={t("fields.descriptionEn")} multi /></> : null}{entity === "lesson" ? <><Field label="Unit id" name="unitId" defaultValue={text(initial, "unitId")} required /><Field label={t("fields.slug")} name="slug" defaultValue={text(initial, "slug")} required /><Localized values={initial} name="title" titleFa={t("fields.titleFa")} titleEn={t("fields.titleEn")} /><Localized values={initial} name="description" titleFa={t("fields.descriptionFa")} titleEn={t("fields.descriptionEn")} multi /><Field label={t("fields.durationSeconds")} name="estimatedDuration" type="number" defaultValue={text(initial, "estimatedDuration")} /><Json label="Objectives JSON" name="objectives" value={json(initial, "objectives")} t={t} /><Json label="Content blocks JSON" name="content" value={json(initial, "content")} t={t} /></> : null}<Field label={t("fields.order")} name="order" type="number" defaultValue={text(initial, "order") || "0"} required /></CardContent></Card><div className="flex flex-wrap gap-3"><Button type="submit" disabled={pending}>{pending ? t("saving") : t("save")}</Button>{state?.ok ? <p className="text-body-sm text-success" role="status">{t("saved")}</p> : state && !state.ok ? <p className="text-body-sm text-destructive" role="alert">{Object.values(state.fieldErrors ?? {}).flat().join(" ") || t(`errors.${state.code}`)}</p> : null}</div></form>;
}
function Localized({ values, name, titleFa, titleEn, multi }: { values: Values; name: string; titleFa: string; titleEn: string; multi?: boolean }) { return <div className="grid gap-4 sm:grid-cols-2"><Field label={titleFa} name={`${name}Fa`} defaultValue={nested(values, name, "fa")} multiline={multi} required /><Field label={titleEn} name={`${name}En`} defaultValue={nested(values, name, "en")} multiline={multi} required /></div>; }
function Json({ label, name, value, t }: { label: string; name: string; value: string; t: ReturnType<typeof useTranslations<"admin">> }) { return <label className="grid gap-2 text-body-sm"><span>{label}</span><Textarea name={name} defaultValue={value} rows={8} /><span className="text-caption text-muted-foreground">{t("help.json")}</span></label>; }
function Field({ label, name, defaultValue, type = "text", required = false, multiline = false }: { label: string; name: string; defaultValue: string; type?: string; required?: boolean; multiline?: boolean }) { return <label className="grid gap-2 text-body-sm"><span>{label}</span>{multiline ? <Textarea name={name} defaultValue={defaultValue} rows={4} required={required} /> : <Input name={name} type={type} defaultValue={defaultValue} required={required} />}</label>; }

export function CurriculumStatusForm({ id, status, action }: { id: string; status: ContentStatus; action: Action }) { const t = useTranslations("admin"); const [state, formAction, pending] = useActionState<AdminActionResult | null, FormData>(action, null); return <Card className="mt-6"><CardHeader><CardTitle>{t("status")}: {t(`statuses.${status}`)}</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-2">{(["published", "draft", "archived"] as const).map((next) => <form key={next} action={formAction}><input type="hidden" name="id" value={id} /><input type="hidden" name="status" value={next} /><Button type="submit" variant={next === "published" ? "default" : "outline"} disabled={pending || status === next}>{t(next === "published" ? "publish" : next === "draft" ? "draft" : "archive")}</Button></form>)}</div>{state && !state.ok ? <p className="mt-3 text-body-sm text-destructive" role="alert">{Object.values(state.fieldErrors ?? {}).flat().join(" ") || t(`errors.${state.code}`)}</p> : null}</CardContent></Card>; }
