import { Activity, ArrowLeft, ArrowRight, BookOpenCheck, BrainCircuit, CheckCircle2, Clock3, Languages, Mic2, Target } from "lucide-react";
import { getTranslations } from "next-intl/server";

import { Container } from "@/components/container";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Link } from "@/i18n/navigation";
import { localize } from "@/lib/learning/localize";
import type { AppLocale } from "@/i18n/routing";
import type { DomainProgressSummary, ProgressDashboardData, Recommendation } from "@/lib/progress/types";

const domainIcons = {
  vocabulary: Languages,
  grammar: BrainCircuit,
  listening: Activity,
  reading: BookOpenCheck,
} as const;

export async function ProgressDashboard({ data, locale }: { data: ProgressDashboardData; locale: AppLocale }) {
  const t = await getTranslations("progress");
  const learningPercent = data.learning.totalLessons ? Math.round((data.learning.completedLessons / data.learning.totalLessons) * 100) : null;
  const accuracyLabel = data.practice.accuracy === null ? t(`practice.evidence.${data.practice.evidence}`) : `${data.practice.accuracy}%`;
  const Arrow = locale === "fa" ? ArrowLeft : ArrowRight;
  const lastActivity = data.activity.lastActivityAt ? new Intl.DateTimeFormat(locale === "fa" ? "fa-IR" : "en-US", { dateStyle: "medium", timeZone: "UTC" }).format(data.activity.lastActivityAt) : null;

  return (
    <main className="flex flex-1 bg-background py-10 md:py-14">
      <Container><div className="mx-auto w-full max-w-6xl">
        <header className="max-w-3xl"><p className="text-label flex items-center gap-3 font-semibold uppercase tracking-[0.14em] text-gold"><span aria-hidden className="eyebrow-rule" />{t("eyebrow")}</p><h1 className="text-h1 mt-3">{t("title")}</h1><p className="text-body mt-4 text-muted-foreground">{t("description")}</p></header>
        <section aria-labelledby="progress-position" className="mt-10"><h2 id="progress-position" className="sr-only">{t("position.title")}</h2><Card className="overflow-hidden"><CardContent className="grid gap-6 p-6 md:grid-cols-[minmax(0,1fr)_18rem] md:p-8"><div><p className="text-label text-gold">{t("position.eyebrow")}</p>{data.learning.level ? <p className="text-body-sm mt-2 text-muted-foreground">{data.learning.level.code} · {localize(data.learning.level.title, locale)}</p> : null}<h2 className="text-h2 mt-3">{data.learning.currentLesson ? localize(data.learning.currentLesson.title, locale) : t("position.noLesson")}</h2><p className="text-body-sm mt-3 max-w-2xl text-muted-foreground">{data.learning.currentLesson ? localize(data.learning.currentLesson.description, locale) : t("position.noLessonDescription")}</p>{data.learning.currentLesson ? <Button asChild size="sm" className="mt-5"><Link href={`/learn/${data.learning.currentLesson.levelSlug}/${data.learning.currentLesson.courseSlug}/${data.learning.currentLesson.unitSlug}/${data.learning.currentLesson.slug}`}>{t("position.continue")}<Arrow aria-hidden className="size-4" /></Link></Button> : null}</div><div className="rounded-xl border border-border bg-muted/40 p-5"><p className="text-body-sm text-muted-foreground">{t("learning.completion")}</p><p className="mt-2 text-4xl font-bold">{learningPercent === null ? "—" : `${learningPercent}%`}</p><p className="text-body-sm mt-2 text-muted-foreground">{t("learning.lessons", { completed: data.learning.completedLessons, total: data.learning.totalLessons })}</p><ProgressBar value={learningPercent} label={t("learning.completion")} /></div></CardContent></Card></section>
        <section aria-labelledby="progress-overview" className="mt-8"><h2 id="progress-overview" className="text-h2" >{t("overview.title")}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><MetricCard icon={Target} title={t("practice.accuracy")} value={accuracyLabel} detail={t("practice.attempts", { count: data.practice.attempts })} /><MetricCard icon={CheckCircle2} title={t("practice.sessions")} value={String(data.practice.completedSessions)} detail={t("practice.correct", { correct: data.practice.correctAnswers })} /><MetricCard icon={Clock3} title={t("activity.title")} value={String(data.activity.activeDaysLast30)} detail={lastActivity ? t("activity.last", { date: lastActivity }) : t("activity.none")} /></div></section>
        <section aria-labelledby="progress-recommendation" className="mt-8"><h2 id="progress-recommendation" className="sr-only">{t("recommendation.title")}</h2><RecommendationCard recommendation={data.recommendation} locale={locale} /></section>
        <section aria-labelledby="progress-domains" className="mt-10"><div className="flex items-end justify-between gap-4"><h2 id="progress-domains" className="text-h2">{t("domains.title")}</h2><p className="text-caption text-muted-foreground">{t("domains.description")}</p></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.domains.map((domain) => <DomainCard key={domain.domain} data={domain} />)}<Card><CardHeader><CardTitle className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-full border border-gold/40 bg-accent"><Mic2 aria-hidden className="size-4 text-gold" /></span>{t("speaking.title")}</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{data.speaking.completedAttempts}</p><p className="text-body-sm mt-2 text-muted-foreground">{data.speaking.completedAttempts ? t("speaking.completed", { count: data.speaking.completedAttempts }) : data.speaking.providerUnavailableAttempts ? t("speaking.providerUnavailable") : t("speaking.noData")}</p></CardContent></Card></div></section>
      </div></Container>
    </main>
  );
}

function MetricCard({ icon: Icon, title, value, detail }: { icon: typeof Target; title: string; value: string; detail: string }) { return <Card><CardContent className="p-5"><span className="flex size-9 items-center justify-center rounded-full border border-gold/40 bg-accent"><Icon aria-hidden className="size-4 text-gold" /></span><p className="text-body-sm mt-4 text-muted-foreground">{title}</p><p className="mt-1 text-3xl font-bold">{value}</p><p className="text-caption mt-2 text-muted-foreground">{detail}</p></CardContent></Card>; }

async function DomainCard({ data }: { data: DomainProgressSummary }) { const t = await getTranslations("progress"); const Icon = domainIcons[data.domain]; const percent = data.domain === "vocabulary" ? null : data.completionPercent; const href = `/${data.domain}`; return <Card><CardHeader><CardTitle className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-full border border-gold/40 bg-accent"><Icon aria-hidden className="size-4 text-gold" /></span>{t(`domains.${data.domain}`)}</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{data.domain === "vocabulary" ? data.knownCount : percent === null ? "—" : `${percent}%`}</p><p className="text-body-sm mt-2 text-muted-foreground">{data.domain === "vocabulary" ? t("domains.known", { known: data.knownCount, learning: data.inProgressCount, total: data.availableCount }) : t("domains.completed", { completed: data.completedCount, total: data.availableCount })}</p>{data.domain !== "vocabulary" ? <ProgressBar value={percent} label={t(`domains.${data.domain}`)} /> : null}<Link href={href} className="mt-4 inline-flex items-center gap-1 text-body-sm font-medium text-primary hover:underline">{t("domains.open")}<ArrowRight aria-hidden className="size-4 rtl:rotate-180" /></Link></CardContent></Card>; }

async function RecommendationCard({ recommendation, locale }: { recommendation: Recommendation | null; locale: AppLocale }) { const t = await getTranslations("progress"); if (!recommendation) return <Card><CardContent className="flex items-start gap-4 p-6"><Target aria-hidden className="mt-1 size-5 text-gold" /><div><h3 className="text-h3">{t("recommendation.title")}</h3><p className="text-body-sm mt-2 text-muted-foreground">{t("recommendation.none")}</p></div></CardContent></Card>; const label = recommendation.targetTitle ? localize(recommendation.targetTitle, locale) : recommendation.targetDomain ? t(`domains.${recommendation.targetDomain}`) : t("recommendation.practice"); return <Card className="border-primary/20 bg-primary/5"><CardContent className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-label text-gold">{t("recommendation.title")}</p><h3 className="text-h3 mt-2">{label}</h3><p className="text-body-sm mt-2 text-muted-foreground">{t(`recommendation.reasons.${recommendation.reason}`)}</p></div><Button asChild size="sm" className="shrink-0"><Link href={recommendation.href}>{t("recommendation.open")}<ArrowRight aria-hidden className="size-4 rtl:rotate-180" /></Link></Button></CardContent></Card>; }

function ProgressBar({ value, label }: { value: number | null; label: string }) { const safeValue = value ?? 0; return <div className="mt-4 h-2 overflow-hidden rounded-full bg-muted" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={safeValue}><div className="progress-fill h-full rounded-full transition-[width] duration-500" style={{ width: `${safeValue}%` }} /></div>; }
